### ISSUE TITLE
KeyError: 'HOME'

### ISSUE THREAD

**Issue by bmWhale** [ColorsWind/WSL-Port-Forwarding#4]
```
 python3 .\port_forwarding.py
Traceback (most recent call last):
  File "D:\port_forwarding.py", line 267, in <module>
    main()
  File "D:\port_forwarding.py", line 219, in main
    config = load_config()
  File "D:\port_forwarding.py", line 194, in load_config
    config_path = os.path.join(os.environ['HOME'], '.wsl-port-forward.json')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
```

Is supported on windows 11 ?

**Comment by ColorsWind** [comment]
Hello bmWhale,
please use this script in WSL console:
1. Open powershell administrators privilege.
2. Type `wsl` (or wsl -d Ubuntu-20.04 etc.).
3. Type port_forwarding in WSL console.
Feel free to give your feedback.
